site_name: CSA
theme: cinder
#use_directory_urls: false
extra_css:
    - css/tablefont.css
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
markdown_extensions:
    - admonition
    - pymdownx.arithmatex
    - pymdownx.details
nav:
- Home: index.md
- Problem Sets:
    - 'Problem Set 1: Hello World': pset01.md
    - 'Problem Set 2: Fahrenheit': pset02.md
    - 'Problem Set 3: Note Frequency': pset03.md
- Labs:
    - 'Lab 1: Easter Sunday': lab01.md
    - 'Lab 2: To Be Posted': lab02.md
- Course Notes: notes.md
- FRQs: frqs.md
- Past Exams: pastexams.md
- References: references.md
- Syllabus: syllabus.md
