site_name: CSA
pages:
    - Home: 'index.md'
    - Problem Sets: 'psets.md'
    - Labs: 'labs.md'
    - Quizzes: 'quizzes.md'
    - Tests: 'tests.md'
    - FRQs: 'frqs.md'
    - Tutorials: 'tutorials.md'
    - Course Info: 'info.md'
theme: mkdocs
