site_name: CSA
theme: cinder
#use_directory_urls: false
extra_css:
    - css/tablefont.css
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
markdown_extensions:
    - admonition
    - pymdownx.arithmatex
    - pymdownx.details
nav:
- Home: index.md
- Problem Sets:
    - 'Problem Set 1: Hello World': pset01.md
    - 'Problem Set 2: Fahrenheit': pset02.md
    - 'Problem Set 3: Note Frequency': pset03.md
    - 'Problem Set 4: Quarterback Rating': pset04.md
    - 'Problem Set 5: Water Meter': pset05.md
    - 'Problem Set 6: Vending Machine': pset06.md
    - 'Problem Set 7: Down Payment': pset07.md
    - 'Problem Set 8: Book Identifier': pset08.md
    - 'Problem Set 9: Radiation Exposure': pset09.md
    - 'Problem Set 10: Credit Card': pset10.md
    - 'Problem Set 11: Vigenere Cipher': pset11.md
    - 'Problem Set 12: Library Rental': pset12.md
- Labs:
    - 'Lab 1: Easter Sunday': lab01.md
    - 'Lab 2: Movie Critic': lab02.md
    - 'Lab 3: Coin Change': lab03.md
    - 'Lab 4: Gene Detection': lab04.md
    - 'Lab 5: Smooth Signal': lab05.md
    - 'Lab 6: Caesar Cipher': lab06.md
    - 'Lab 7: Polybius Cipher': lab07.md
    - 'Lab 8: Substitution Cipher': lab08.md
    - 'Lab 9: Request Line': lab09.md
- Course Notes: notes.md
- FRQs: frqs.md
- Prior Tests: priortests.md
- References: references.md
- Syllabus: syllabus.md
